# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = "¿Quienes somos?"
  url = "#quienes-somos"
  weight = 10

[[main]]
  name = "Asociaciones"
  url = "#asociaciones"
  weight = 20

[[main]]
  name = "Blog"
  url = "#blog"
  weight = 30

[[main]]
  name = "Periódico"
  url = "#periodico"
  weight = 40

[[main]]
  name = "Proyectos"
  url = "#proyectos"
  weight = 50

[[main]]
  name = "Contacto"
  url = "#contacto"
  weight = 60
